dependencies {
    api project(":customers-service-api-web")
    api project(":customers-service-api-messaging")
    api project(":orders-service-api-messaging")
    api project(":common-swagger")

    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'io.rest-assured:spring-mock-mvc'

    api "org.springframework.boot:spring-boot-starter-web"
    api "org.springframework.boot:spring-boot-starter-actuator"
    api "io.eventuate.local.java:eventuate-local-java-spring-jdbc-starter"

    testImplementation 'com.pholser:junit-quickcheck-core:0.7'
    testImplementation 'com.pholser:junit-quickcheck-generators:0.7'
    testImplementation "junit:junit:4.13.2"
    testRuntimeOnly "org.junit.vintage:junit-vintage-engine"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "io.eventuate.local.java:eventuate-client-java-spring-jdbc"

}
