version: '3'
services:
  zookeeper:
    image: eventuateio/eventuate-zookeeper:$EVENTUATE_COMMON_VERSION
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: -Xmx64m

  kafka:
    image: "eventuateio/eventuate-kafka:$EVENTUATE_MESSAGING_KAFKA_IMAGE_VERSION"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx192m

  postgres:
    image: eventuateio/eventuate-postgres:$EVENTUATE_COMMON_VERSION
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate


  cdc-service:
    image: eventuateio/eventuate-cdc-service:$EVENTUATE_CDC_VERSION
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_TEST_ON_BORROW: "true"
      SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING_PROFILES_ACTIVE: PostgresWal
      EVENTUATELOCAL_CDC_READER_NAME: PostgresWalReader
      EVENTUATE_CDC_TYPE: "EventuateLocal"
      EVENTUATE_OUTBOX_ID: 1
      JAVA_OPTS: -Xmx64m

  mongodb:
    image: mongo:3.6
    hostname: mongodb
    command: mongod --smallfiles
    ports:
      - "27017:27017"

  customers-service:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    build:
      context: ./customers-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    image: eventuateexamples/eventuate-examples-java-customers-and-orders-customer-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

  orders-history-view-service:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    build:
      context: ./orders-history-view-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    image: eventuateexamples/eventuate-examples-java-customers-and-orders-order-history-service
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
      - postgres
      - kafka
      - zookeeper
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/customers_and_orders
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

  orders-service:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    build:
      context: ./orders-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    image: eventuateexamples/eventuate-examples-java-customers-and-orders-order-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
      - customers-service
    environment:
      CUSTOMER_SERVICE_URL: http://customers-service:8080/customers/{customerId}
      ENDPOINTS_SENSITIVE: "false"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
