customercommandside:
  build: ./customers-service/
  ports:
    - "8081:8080"

orderhistoryqueryside:
  build: ./orders-history-view-service/
  ports:
    - "8082:8080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/clients_and_orders

ordercommandside:
  build: ./orders-service/
  ports:
    - "8083:8080"

mongodb:
  image: mongo:3.0.4
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"
