

deployUrl=
eventuateMavenRepoUrl=https://snapshots.repositories.eventuate.io/repository,file:///Users/cer/.m2/testdeploy

dockerComposePluginVersion=0.17.7
springBootVersion=3.4.7

junitVersion=5.12.2
junitPlatformLauncherVersion=1.12.2

eventuateUtilVersion=0.20.0.BUILD-SNAPSHOT
eventuateExamplesBaseImageVersion=BUILD-16

eventuateCommonVersion=0.22.0.BUILD-SNAPSHOT

eventuateBomVersion=2026.1.BUILD-SNAPSHOT

eventuateCommonImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateMessagingKafkaImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateCdcImageVersion=0.20.0.BUILD-SNAPSHOT
springDocOpenApiUiVersion=2.8.6
springRetryVersion=2.0.11
