dependencies {
    testImplementation project(":customers-service-api-messaging")
    testImplementation project(":orders-service-api-messaging")

    testImplementation "org.springframework.boot:spring-boot-starter-jdbc"
    testImplementation "org.springframework.boot:spring-boot-starter-test"

    testRuntimeOnly 'com.mysql:mysql-connector-j'
    testRuntimeOnly ('org.postgresql:postgresql') {
        exclude group: "org.slf4j", module: "slf4j-simple"
    }
    testRuntimeOnly 'com.microsoft.sqlserver:mssql-jdbc'
}

test {
    if (!project.ext.has("verifyDbIdMigration")) {
        exclude '**/DbIdMigrationVerificationTest**'
    }

    forkEvery 1
}
