apply plugin: 'docker-compose'

dockerCompose.isRequiredBy(test)

dockerCompose {
    environment.put "EVENTUATE_COMMON_VERSION", eventuateCommonImageVersion
    environment.put "EVENTUATE_MESSAGING_KAFKA_IMAGE_VERSION", eventuateMessagingKafkaImageVersion
    environment.put "EVENTUATE_CDC_VERSION", eventuateCdcImageVersion
    environment.put "EVENTUATE_JAVA_BASE_IMAGE_VERSION", eventuateExamplesBaseImageVersion

    projectName = null

    if ("postgres,EventuatePolling".equals(System.getenv("SPRING_PROFILES_ACTIVE")))
        useComposeFiles = ['../docker-compose-eventuate-local-postgres-polling.yml']
    else if ("postgres,PostgresWal".equals(System.getenv("SPRING_PROFILES_ACTIVE")))
        useComposeFiles = ['../docker-compose-eventuate-local-postgres-wal.yml']
    else useComposeFiles = ['../docker-compose-eventuate-local-mysql-binlog.yml']

    startedServices = ['customers-service']
}

dependencies {
    api project(":orders-service-api-web")
    api project(":customers-service-api-messaging")
    api project(":orders-service-api-messaging")
    api project(":common-swagger")

    api "org.springframework.boot:spring-boot-starter"
    api "org.springframework.boot:spring-boot-starter-web"
    api "org.springframework.boot:spring-boot-starter-actuator"
    api "io.eventuate.local.java:eventuate-local-java-spring-jdbc-starter"

    testImplementation "io.eventuate.local.java:eventuate-client-java-spring-jdbc"
    testImplementation project(":customers-service-api-web")
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "io.eventuate.local.java:eventuate-client-java-spring-jdbc"
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation "com.jayway.jsonpath:json-path"
}
