buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE"
        // if using Stub Runner (consumer side) only remove this dependency
        classpath "org.springframework.cloud:spring-cloud-contract-gradle-plugin:1.1.1.RELEASE"
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
    }
}



apply plugin: "io.spring.dependency-management"
apply plugin: 'docker-compose'

dockerCompose.isRequiredBy(test)

dependencyManagement {
    imports {
            mavenBom 'org.springframework.cloud:spring-cloud-contract-dependencies:2.2.5.RELEASE'
    }
}

apply plugin: 'org.springframework.boot'

dockerCompose {
    environment.put "EVENTUATE_COMMON_VERSION", eventuateCommonImageVersion
    environment.put "EVENTUATE_MESSAGING_KAFKA_IMAGE_VERSION", eventuateMessagingKafkaImageVersion
    environment.put "EVENTUATE_CDC_VERSION", eventuateCdcImageVersion
    environment.put "EVENTUATE_JAVA_BASE_IMAGE_VERSION", eventuateExamplesBaseImageVersion

    projectName = null

    if ("postgres,EventuatePolling".equals(System.getenv("SPRING_PROFILES_ACTIVE")))
        useComposeFiles = ['../docker-compose-eventuate-local-postgres-polling.yml']
    else if ("postgres,PostgresWal".equals(System.getenv("SPRING_PROFILES_ACTIVE")))
        useComposeFiles = ['../docker-compose-eventuate-local-postgres-wal.yml']
    else useComposeFiles = ['../docker-compose-eventuate-local-mysql-binlog.yml']

    startedServices = ['customers-service']
}

dependencies {
    api project(":orders-service-api-web")
    api project(":customers-service-api-messaging")
    api project(":orders-service-api-messaging")
    api project(":common-swagger")

    api "org.springframework.boot:spring-boot-starter:$springBootVersion"
    api "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    api "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"
    api "io.eventuate.local.java:eventuate-local-java-spring-jdbc-starter"


    testImplementation "net.chrisrichardson.eventstore.examples.customersandorders:common-contracts:1.0-SNAPSHOT:stubs"

    testImplementation "io.eventuate.local.java:eventuate-client-java-spring-jdbc"
    testImplementation project(":customers-service-api-web")
    testImplementation "org.springframework.cloud:spring-cloud-contract-wiremock"
    testImplementation "org.springframework.cloud:spring-cloud-starter-contract-stub-runner"
    testImplementation "junit:junit:4.12"
    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
    testImplementation "io.eventuate.local.java:eventuate-client-java-spring-jdbc"
    testImplementation 'com.jayway.restassured:rest-assured:2.3.0'
    testImplementation "com.jayway.jsonpath:json-path:2.3.0"
}
