dependencies {
    testImplementation project(":common-test")
    testImplementation project(":customers-service-api-web")
    testImplementation project(":orders-service-api-web")

    testImplementation "org.springframework.boot:spring-boot-starter-web"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
}

test {
    ignoreFailures (!project.hasProperty("ignoreE2EFailures") || ignoreE2EFailures.toBoolean())
}
