dependencies {
    testImplementation project(":common-test")
    testImplementation project(":customers-service-api-web")
    testImplementation project(":orders-service-api-web")

    testImplementation "junit:junit:4.12"
    testImplementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
}

test {
    ignoreFailures (!project.hasProperty("ignoreE2EFailures") || ignoreE2EFailures.toBoolean())
}
