apply plugin: VerifyMongoDBConfigurationPlugin

apply plugin: 'docker-compose'

dockerCompose.isRequiredBy(test)

dockerCompose {
    useComposeFiles = ['docker-compose-integration-tests.yml']
}

dependencies {
    api project(":orders-history-view-service-api-web")

    api project(":orders-service-api-messaging")
    api project(":customers-service-api-messaging")

    api project(":common-swagger")

    api "org.springframework.boot:spring-boot-starter-web"
    api "org.springframework.boot:spring-boot-starter-actuator"
    api "org.springframework.boot:spring-boot-starter-data-mongodb"
    api "org.springframework.retry:spring-retry:$springRetryVersion"

    api "io.eventuate.local.java:eventuate-local-java-spring-events-starter"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
}
